# Generated by Django 4.2.7 on 2023-11-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
    ]