# Generated by Django 4.2.7 on 2023-11-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date_added",)},
        ),
    ]